# Generated by Django 5.0 on 2025-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prosthetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название протеза на рус')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название протеза на узб')),
                ('description_ru', models.TextField(max_length=600, verbose_name='Описание на рус')),
                ('description_uz', models.TextField(max_length=600, verbose_name='Описание на узб')),
                ('image', models.ImageField(upload_to='images/prosthetics/')),
                ('type_prosthetics', models.CharField(choices=[('hand_prosthetics', 'Протез руки'), ('foot_prosthetics', 'Протез ноги')], max_length=100, verbose_name='Тип протеза')),
            ],
            options={
                'verbose_name': 'Протез',
                'verbose_name_plural': 'Протезы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_review', models.ImageField(upload_to='images/reviews/', verbose_name='Картинка для отзывов')),
                ('name_review_ru', models.CharField(max_length=100, verbose_name='Имя человека для отзыва на рус')),
                ('name_review_uz', models.CharField(max_length=100, verbose_name='Имя человека для отзыва на узб')),
                ('description_review_ru', models.TextField(max_length=1000, verbose_name='Описание отзыва на рус')),
                ('description_review_uz', models.TextField(max_length=1000, verbose_name='Описание отзыва на узб')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_staff_ru', models.CharField(max_length=100, verbose_name='Имя сотрудника на рус')),
                ('name_staff_uz', models.CharField(max_length=100, verbose_name='Имя сотрудника на узб')),
                ('position_staff_ru', models.CharField(max_length=100, verbose_name='Должность сотрудника на рус')),
                ('position_staff_uz', models.CharField(max_length=100, verbose_name='Должность сотрдуника на узб')),
                ('description_staff_ru', models.TextField(max_length=1000, verbose_name='Описание на рус')),
                ('description_staff_uz', models.TextField(max_length=1000, verbose_name='Описание на узб')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
