# Generated by Django 5.0 on 2025-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthetics',
            name='status',
            field=models.CharField(choices=[('ready', 'готов'), ('coming', 'скоро')], default=1, max_length=100, verbose_name='Статус протеза'),
            preserve_default=False,
        ),
    ]
