# Generated by Django 5.0 on 2025-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_prosthetics_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image_staff',
            field=models.ImageField(default=1, upload_to='images/staff/', verbose_name='Картинка сотрудника'),
            preserve_default=False,
        ),
    ]
