# Generated by Django 5.0 on 2025-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_staff_image_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosthetics',
            name='type_prosthetics',
        ),
        migrations.AddField(
            model_name='prosthetics',
            name='type_prosthetics_ru',
            field=models.CharField(choices=[('hand_prosthetics', 'Протез руки'), ('foot_prosthetics', 'Протез ноги')], default=1, max_length=100, verbose_name='Тип протеза на рус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prosthetics',
            name='type_prosthetics_uz',
            field=models.CharField(blank=True, choices=[('hand_prosthetics', "Protez qo'l"), ('foot_prosthetics', 'Protez oyoq')], max_length=100, null=True, verbose_name='Тип протеза на узб'),
        ),
    ]
